table 'Dim Product'
	lineageTag: 8f08c8c4-8012-4517-ae7e-92485f0045f8

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 7c4552bd-98bf-4076-8517-86b70470c3b0
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: 1bb966d0-e6a4-42f5-82a1-e2ab9a31ea33
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 965c7692-bd9e-474e-9b1b-07ba2f4b42f8
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: fd333a5f-483a-42cd-b330-5af1c68bb82f
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column premium_type
		dataType: string
		lineageTag: 56170c59-f0d2-495c-9b59-abf9b32c1d94
		summarizeBy: none
		sourceColumn: premium_type

		annotation SummarizationSetBy = Automatic

	partition 'Dim Product' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Satish Oleti\Downloads\Assignment\data\dim_product.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_code", type text}, {"product_name", type text}, {"product_category", type text}, {"premium_type", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

