table 'Dim Agent'
	lineageTag: 5399e248-eb50-40e2-beb4-473262b8d77b

	column agent_id
		dataType: int64
		formatString: 0
		lineageTag: 429b348a-ec69-4053-9109-b61268cabf33
		summarizeBy: none
		sourceColumn: agent_id

		annotation SummarizationSetBy = Automatic

	column agent_code
		dataType: string
		lineageTag: 0db55cab-5288-4e06-97e1-31b140beed84
		summarizeBy: none
		sourceColumn: agent_code

		annotation SummarizationSetBy = Automatic

	column agent_name
		dataType: string
		lineageTag: f9414b2d-7bb7-4455-a94b-e1aad411f10a
		summarizeBy: none
		sourceColumn: agent_name

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 5ce58510-7ca6-440c-838f-2b3795df1090
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column territory
		dataType: string
		lineageTag: 51fd7e74-e5cb-4aa6-8890-f10f47704dbf
		summarizeBy: none
		sourceColumn: territory

		annotation SummarizationSetBy = Automatic

	column office
		dataType: string
		lineageTag: 80dbebc1-b9fe-41ed-b16f-a1557b2ece98
		summarizeBy: none
		sourceColumn: office

		annotation SummarizationSetBy = Automatic

	column join_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 09062020-dc0f-4109-bf33-3363fc609409
		summarizeBy: none
		sourceColumn: join_date

		variation Variation
			isDefault
			relationship: b5bc230a-a655-4fb5-85de-cc504e124726
			defaultHierarchy: LocalDateTable_ad172263-726d-422d-b30e-242aefb57511.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column channel
		dataType: string
		lineageTag: ca222f1f-bc84-4d4c-8ecb-33fd7bfb02e9
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column active_flag
		dataType: int64
		formatString: 0
		lineageTag: 82d1a35b-fffa-46c3-9b73-dd0f2273c741
		summarizeBy: sum
		sourceColumn: active_flag

		annotation SummarizationSetBy = Automatic

	partition 'Dim Agent' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Satish Oleti\Downloads\Assignment\data\dim_agent.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"agent_id", Int64.Type}, {"agent_code", type text}, {"agent_name", type text}, {"region", type text}, {"territory", type text}, {"office", type text}, {"join_date", type date}, {"channel", type text}, {"active_flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

