table 'Dim Date'
	lineageTag: 27eb2c43-7d3f-40b9-bf1a-58fe7a0c0ee2

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 719f7a6e-8b6e-4d1b-ba08-b0b46a630580
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6c752c7d-b3ef-4bea-bf76-5efb4da28208
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 9e2bf4c3-82d3-4958-beab-5e8009c559cd
			defaultHierarchy: LocalDateTable_b63b3f71-6323-44cd-89df-76a37a41b1d6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: aa587976-47bd-4c73-8d5f-1486fbcc4729
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: eb5cc57c-ec2f-4e47-b249-ff14d2e16dce
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 2d5c9ab2-8cbc-4792-9b89-1fa003332e74
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 89a35faf-6378-44c7-86c6-4adf8dd6966b
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: 22e155c8-97aa-495e-8466-87fd8537b74a
		summarizeBy: sum
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		formatString: 0
		lineageTag: f490a6b6-4458-45ad-8872-9019faf6505b
		summarizeBy: sum
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column is_weekday
		dataType: int64
		formatString: 0
		lineageTag: 818fc88b-313a-447b-a669-c04a77cb5c6d
		summarizeBy: sum
		sourceColumn: is_weekday

		annotation SummarizationSetBy = Automatic

	partition 'Dim Date' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Satish Oleti\Downloads\Assignment\data\dim_date.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"fiscal_year", Int64.Type}, {"fiscal_quarter", Int64.Type}, {"is_weekday", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

