table 'Fact Target'
	lineageTag: 4e2201cd-532e-4f07-b9bc-ebec8300438d

	column agent_id
		dataType: int64
		formatString: 0
		lineageTag: 6c6d8974-92f8-459d-af8f-2a6a4617dba2
		summarizeBy: none
		sourceColumn: agent_id

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 85fa2fa0-d88c-4faa-8c5a-3777affcfa09
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 98e62525-584f-4698-a093-5e0fb55c505e
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column ape_target_usd
		dataType: double
		lineageTag: ff3f3719-cc0a-40b8-8bbb-ed11d6c6af06
		summarizeBy: sum
		sourceColumn: ape_target_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Target' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Satish Oleti\Downloads\Assignment\data\fact_target.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"agent_id", Int64.Type}, {"year", Int64.Type}, {"month", Int64.Type}, {"ape_target_usd", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

