table 'Fact Sales'
	lineageTag: 9d5fd7e4-7793-40f1-ae82-947d4dbdcb16

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 2d8de358-2b35-458e-b333-aa195fdc8121
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 71bbe462-d28d-4821-8ce5-3cb8c382a67b
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column agent_id
		dataType: int64
		formatString: 0
		lineageTag: 97861aa2-d6f1-48d9-8627-fd95f0477024
		summarizeBy: none
		sourceColumn: agent_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 2bf5bcd8-3772-4ab5-965f-8802508104af
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column ape_usd
		dataType: double
		lineageTag: 69864083-0d14-4029-ab05-e3ad04730818
		summarizeBy: sum
		sourceColumn: ape_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fyp_usd
		dataType: double
		lineageTag: e1aae201-ca4e-43fe-b6e5-305eb14883c1
		summarizeBy: sum
		sourceColumn: fyp_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column policies_issued
		dataType: int64
		formatString: 0
		lineageTag: 68156203-d99d-4e57-ad26-250dd365ec1d
		summarizeBy: sum
		sourceColumn: policies_issued

		annotation SummarizationSetBy = Automatic

	column sale_channel
		dataType: string
		lineageTag: c920450e-c41f-430b-8f51-aedff50e24a1
		summarizeBy: none
		sourceColumn: sale_channel

		annotation SummarizationSetBy = Automatic

	partition 'Fact Sales' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Satish Oleti\Downloads\Assignment\data\fact_sales.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date_key", Int64.Type}, {"agent_id", Int64.Type}, {"product_id", Int64.Type}, {"ape_usd", type number}, {"fyp_usd", type number}, {"policies_issued", Int64.Type}, {"sale_channel", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

